apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: ghcr.io/2022-4400-exp/4439-go-helloworld-2:50b6d9ecb29a5ee083338981ba6b09bef18f4e78@sha256:60781efa773d59d78dab0be80f5f807b9e46443b7ed6c52fe1804f9816ea530d
        name: go-helloworld-2
---