apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
        - image: ghcr.io/2022-4400-exp/4439-go-helloworld-2:288d700d83d0f43f6ef7b90d119c313755724964
          name: go-helloworld-2
---
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/2022-4400-exp/4439-go-helloworld-2:288d700d83d0f43f6ef7b90d119c313755724964
